### ISSUE TITLE
WARNING:tensorflow:From ./tools/classify-hangul.py:56: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-hangul-recognition#26]
WARNING:tensorflow:From ./tools/classify-hangul.py:56: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.

**Comment by markstur** [comment]
@pvaneck time to look at the deprecation warnings?

**Comment by pvaneck** [comment]
Yea, I will take a look.
