### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte

### ISSUE THREAD

**Issue by PRISHIta123** [IBM/tensorflow-hangul-recognition#39]
I am getting this error when trying to convert the image-files to TFrecords. Can someone suggest a solution?

**Comment by stevemart** [comment]
@pvaneck please address ^

**Comment by pvaneck** [comment]
Hey, were you able to generate the images okay using the hangul-image-generator.py script?

This type of error makes me think something happened to the label-file (e.g. labels/256-common-hangul.txt) or the generated image labels csv file (e.g. image-data/labels-map.csv) to cause some non utf-8 character to sneak in. Or maybe the encoding of one of the files somehow got changed?

Running the scripts as is: 
```
python ./tools/hangul-image-generator.py --label-file ./labels/256-common-hangul.txt
python ./tools/convert-to-tfrecords.py --label-file ./labels/256-common-hangul.txt
```
works fine for me in both python 3.6 and 2.7 (on Mac OS).

**Comment by pvaneck** [comment]
Some images being blank or just a dot is likely indicative of one or more of the font files being used not supporting Korean characters. If you can, double check the fonts, and then test on a smaller subset of fonts and characters. First clear the 'image-data' directory and try running the following with maybe one or two fonts to see if the workflow can work on your system:

```
python ./tools/hangul-image-generator.py --label-file ./labels/256-common-hangul.txt
python ./tools/convert-to-tfrecords.py --label-file ./labels/256-common-hangul.txt
```

**Comment by PRISHIta123** [comment]
I deleted some fonts that did not support all korean characters, it worked after that. Thanks for the help.
