### ISSUE TITLE
How to build a new model from images different size (not 64x6x) ?

### ISSUE THREAD

**Issue by helium390** [IBM/tensorflow-hangul-recognition#43]
I have 5000 pictures (words) with size 64xA (A - is length of word). How can I build a new model and train it?

**Comment by stevemart** [comment]
@pvaneck can you take a look at this issue? FYI @dolph

**Comment by helium390** [comment]
In this project only letters were generated and trained. But I want to use words (not letters).

**Comment by kspook** [comment]
hi, pvneck

https://github.com/emedvedev/attention-ocr

attention-ocr is really word image classification?
i followed instruction on test and visualizaition attention results.
python src/launcher.py --phase=test --visualize --data-path=evaluation_data/svt/test.txt --data-base-dir=evaluation_data/svt --log-path=log.txt --load-model --model-dir=model --output-dir=results


--data-path=evaluation_data/svt/test.txt    contains  the cropped image's path and "word"

and silly-looking, the command makes  results. T.T
