### ISSUE TITLE
Seems like the arch image should include the training

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-hangul-recognition#7]
Not sure about this, but the arch image is the running app and doesn't really try to show the input/training parts.  Might be worth trying to show both in the one picture.

**Comment by pvaneck** [comment]
Added a little bit more to at least cover the training a little bit to the diagram in b5d234301f3514d88d705a59fee8caf878659ef2

**Comment by markstur** [comment]
Was closed long ago w/ the previous comment
